#!/usr/bin/python3
"""Module that factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv


def factorize(valu):
    """"print a simple descomposition of an integer > 1"""
    i = 2

    if valu < 2:
        return
    print()
    print(valu, "<- valu-bef")
    while valu % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(valu, valu / i, i))
    print(valu, "<- valu-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            valu = int(line.split('\n')[0])
            factorize(valu)
            line = file.readline()
except:
    pass
